import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsString } from 'class-validator';

export class GoogleLoginDto {
  @ApiProperty({
    example: 'eyJhbGciOiJSUzI1NiIs...',
    description: 'The ID Token generated by the Google SDK on Android',
  })
  @IsString()
  @IsNotEmpty()
  id_token!: string;
}
